namespace EdmxSourceGenerator.Internal;

using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using YamlDotNet.RepresentationModel;

internal class MetaData
{
    internal MetaData(string content, List<EdmxFile> edmxFiles)
    {
        this.Content = content;
        this.EdmxFiles = edmxFiles;
    }

    internal List<EdmxFile> EdmxFiles { get; private set; }
    private string Content { get; set; }

    internal string GenerateCode()
    {
        var result = string.Empty;
        if (this.EdmxFiles.Any())
        {
            result = $@"// <auto-generated/>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

";
            if (this.EdmxFiles.Count == 1)
            {
                var edmxFile = this.EdmxFiles[0];
                result += $@"namespace {edmxFile.Namespace};
{this.WriteEntityMetadata()}";
            }
            else
            {
                foreach (var edmxFile in this.EdmxFiles)
                {
                    result += $@"namespace {edmxFile.Namespace}
{{
{this.WriteEntityMetadata(true)}}}
";
                }
            }
        }

        return result;
    }

    private string WriteEntityMetadata(bool indent = false)
    {
        // Setup the input
        using var content = new StringReader(this.Content);

        // Load the stream
        var yaml = new YamlStream();
        yaml.Load(content);

        var result = string.Empty;
        var mapping = (YamlMappingNode)yaml.Documents.First().RootNode;
        foreach (var node in mapping.Children)
        {
            result += $@"
{(indent ? "    " : "")}[MetadataType(typeof({node.Key}MetaData))]
{(indent ? "    " : "")}public partial class {node.Key}
{(indent ? "    " : "")}{{
{(indent ? "    " : "")}    private sealed class {node.Key}MetaData
{(indent ? "    " : "")}    {{
";
            foreach (var valueNode in ((YamlSequenceNode)node.Value).Children)
            {
                foreach (var child in ((YamlMappingNode)valueNode).Children)
                {
                    var _type = string.Empty;
                    foreach (var tmp1 in ((YamlSequenceNode)child.Value).Children)
                    {
                        foreach (var __type in ((YamlMappingNode)tmp1).Children.Where(n => n.Key.ToString() == "PropertyType"))
                        {
                            _type = __type.Value.ToString();
                        }

                        foreach (var tmp2 in ((YamlMappingNode)tmp1).Children.Where(n => n.Key.ToString() == "attributes"))
                        {
                            foreach (var attributes in ((YamlSequenceNode)tmp2.Value).Children)
                            {
                                result += $@"{(indent ? "    " : "")}        [{attributes}]
";
                            }
                        }
                    }

                    result += $@"{(indent ? "    " : "")}        public {_type} {child.Key} {{ get; set; }}
";
                }
            }

            result += $@"{(indent ? "    " : "")}    }}
{(indent ? "    " : "")}}}
";
        }

        return result;
    }
}
